[env]
#TERM = "screen-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 1.0

[font]
normal.family = "MesloLGS Nerd Font Mono"

[general]
# Source local configuration
import = [
    "~/.config/alacritty/alacritty.local.toml",
    "~/.config/alacritty/rose-pine.toml"
]
